/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminWorkspacesIndexRouteImport } from './routes/_admin/workspaces/index'
import { Route as AdminWorkspacesCreateRouteImport } from './routes/_admin/workspaces/create'
import { Route as AdminWorkspacesWorkspaceIdRouteImport } from './routes/_admin/workspaces/$workspaceId'
import { Route as AdminWorkspacesWorkspaceIdIndexRouteImport } from './routes/_admin/workspaces/$workspaceId/index'
import { Route as AdminWorkspacesWorkspaceIdProjectsIndexRouteImport } from './routes/_admin/workspaces/$workspaceId/projects/index'
import { Route as AdminWorkspacesWorkspaceIdClustersIndexRouteImport } from './routes/_admin/workspaces/$workspaceId/clusters/index'
import { Route as AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport } from './routes/_admin/workspaces/$workspaceId/projects/$projectId/index'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesCreateRoute = AdminWorkspacesCreateRouteImport.update({
  id: '/workspaces/create',
  path: '/workspaces/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesWorkspaceIdRoute =
  AdminWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWorkspacesWorkspaceIdIndexRoute =
  AdminWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesWorkspaceIdRoute,
  } as any)
const AdminWorkspacesWorkspaceIdProjectsIndexRoute =
  AdminWorkspacesWorkspaceIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AdminWorkspacesWorkspaceIdRoute,
  } as any)
const AdminWorkspacesWorkspaceIdClustersIndexRoute =
  AdminWorkspacesWorkspaceIdClustersIndexRouteImport.update({
    id: '/clusters/',
    path: '/clusters/',
    getParentRoute: () => AdminWorkspacesWorkspaceIdRoute,
  } as any)
const AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute =
  AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AdminWorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/workspaces': typeof AdminWorkspacesIndexRoute
  '/workspaces/$workspaceId/': typeof AdminWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/clusters': typeof AdminWorkspacesWorkspaceIdClustersIndexRoute
  '/workspaces/$workspaceId/projects': typeof AdminWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/workspaces': typeof AdminWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/clusters': typeof AdminWorkspacesWorkspaceIdClustersIndexRoute
  '/workspaces/$workspaceId/projects': typeof AdminWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRouteWithChildren
  '/_admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/_admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/_admin/workspaces/$workspaceId/': typeof AdminWorkspacesWorkspaceIdIndexRoute
  '/_admin/workspaces/$workspaceId/clusters/': typeof AdminWorkspacesWorkspaceIdClustersIndexRoute
  '/_admin/workspaces/$workspaceId/projects/': typeof AdminWorkspacesWorkspaceIdProjectsIndexRoute
  '/_admin/workspaces/$workspaceId/projects/$projectId/': typeof AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/clusters'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/workspaces/create'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/clusters'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/auth/login'
    | '/_admin/workspaces/$workspaceId'
    | '/_admin/workspaces/create'
    | '/_admin/workspaces/'
    | '/_admin/workspaces/$workspaceId/'
    | '/_admin/workspaces/$workspaceId/clusters/'
    | '/_admin/workspaces/$workspaceId/projects/'
    | '/_admin/workspaces/$workspaceId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/workspaces/': {
      id: '/_admin/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workspaces/create': {
      id: '/_admin/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AdminWorkspacesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workspaces/$workspaceId': {
      id: '/_admin/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workspaces/$workspaceId/': {
      id: '/_admin/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesWorkspaceIdRoute
    }
    '/_admin/workspaces/$workspaceId/projects/': {
      id: '/_admin/workspaces/$workspaceId/projects/'
      path: '/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdProjectsIndexRouteImport
      parentRoute: typeof AdminWorkspacesWorkspaceIdRoute
    }
    '/_admin/workspaces/$workspaceId/clusters/': {
      id: '/_admin/workspaces/$workspaceId/clusters/'
      path: '/clusters'
      fullPath: '/workspaces/$workspaceId/clusters'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdClustersIndexRouteImport
      parentRoute: typeof AdminWorkspacesWorkspaceIdRoute
    }
    '/_admin/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_admin/workspaces/$workspaceId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesWorkspaceIdRoute
    }
  }
}

interface AdminWorkspacesWorkspaceIdRouteChildren {
  AdminWorkspacesWorkspaceIdIndexRoute: typeof AdminWorkspacesWorkspaceIdIndexRoute
  AdminWorkspacesWorkspaceIdClustersIndexRoute: typeof AdminWorkspacesWorkspaceIdClustersIndexRoute
  AdminWorkspacesWorkspaceIdProjectsIndexRoute: typeof AdminWorkspacesWorkspaceIdProjectsIndexRoute
  AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute: typeof AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}

const AdminWorkspacesWorkspaceIdRouteChildren: AdminWorkspacesWorkspaceIdRouteChildren =
  {
    AdminWorkspacesWorkspaceIdIndexRoute: AdminWorkspacesWorkspaceIdIndexRoute,
    AdminWorkspacesWorkspaceIdClustersIndexRoute:
      AdminWorkspacesWorkspaceIdClustersIndexRoute,
    AdminWorkspacesWorkspaceIdProjectsIndexRoute:
      AdminWorkspacesWorkspaceIdProjectsIndexRoute,
    AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute:
      AdminWorkspacesWorkspaceIdProjectsProjectIdIndexRoute,
  }

const AdminWorkspacesWorkspaceIdRouteWithChildren =
  AdminWorkspacesWorkspaceIdRoute._addFileChildren(
    AdminWorkspacesWorkspaceIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminWorkspacesWorkspaceIdRoute: typeof AdminWorkspacesWorkspaceIdRouteWithChildren
  AdminWorkspacesCreateRoute: typeof AdminWorkspacesCreateRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminWorkspacesWorkspaceIdRoute: AdminWorkspacesWorkspaceIdRouteWithChildren,
  AdminWorkspacesCreateRoute: AdminWorkspacesCreateRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
