/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedWorkspacesCreateRouteImport } from './routes/_authenticated/workspaces/create'
import { Route as AuthenticatedWorkspacesWorkspaceIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/settings'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/members/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdClustersIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/clusters/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId'
import { Route as AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/clusters/$clusterId'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/settings'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/create'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/volumes'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/settings'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/metrics'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/logs'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/environment'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/domains'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesCreateRoute =
  AuthenticatedWorkspacesCreateRouteImport.update({
    id: '/workspaces/create',
    path: '/workspaces/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdClustersIndexRouteImport.update({
    id: '/clusters/',
    path: '/clusters/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute =
  AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRouteImport.update({
    id: '/clusters/$clusterId',
    path: '/clusters/$clusterId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteImport.update(
    {
      id: '/_services/$projectId',
      path: '/$projectId',
      getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteImport.update(
    {
      id: '/services',
      path: '/services',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteImport.update(
    {
      id: '/services',
      path: '/services',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRouteImport.update(
    {
      id: '/create',
      path: '/create',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteImport.update(
    {
      id: '/$serviceId',
      path: '/$serviceId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRouteImport.update(
    {
      id: '/volumes',
      path: '/volumes',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRouteImport.update(
    {
      id: '/metrics',
      path: '/metrics',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRouteImport.update(
    {
      id: '/logs',
      path: '/logs',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRouteImport.update(
    {
      id: '/environment',
      path: '/environment',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRouteImport.update(
    {
      id: '/domains',
      path: '/domains',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/clusters/$clusterId': typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteWithChildren
  '/workspaces/$workspaceId/clusters': typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
  '/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services/create': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute
  '/workspaces/$workspaceId/projects/$projectId/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/domains': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/clusters/$clusterId': typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  '/workspaces/$workspaceId/clusters': typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services/create': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/domains': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRouteWithChildren
  '/_authenticated/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/clusters/$clusterId': typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/clusters/': typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  '/_authenticated/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/create': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/domains': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute
  '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/clusters/$clusterId'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/clusters'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects/'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/'
    | '/workspaces/$workspaceId/projects/$projectId/services/create'
    | '/workspaces/$workspaceId/projects/$projectId/services/'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/domains'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/workspaces/create'
    | '/workspaces'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/clusters/$clusterId'
    | '/workspaces/$workspaceId/clusters'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/projects/$projectId/services/create'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/domains'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/workspaces/create'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceId/projects'
    | '/_authenticated/workspaces/$workspaceId/settings'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/$workspaceId/clusters/$clusterId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId'
    | '/_authenticated/workspaces/$workspaceId/clusters/'
    | '/_authenticated/workspaces/$workspaceId/members/'
    | '/_authenticated/workspaces/$workspaceId/projects/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/create'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/domains'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/environment'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/logs'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/metrics'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/settings'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/volumes'
    | '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/create': {
      id: '/_authenticated/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings': {
      id: '/_authenticated/workspaces/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects': {
      id: '/_authenticated/workspaces/$workspaceId/projects'
      path: '/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/': {
      id: '/_authenticated/workspaces/$workspaceId/members/'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/clusters/': {
      id: '/_authenticated/workspaces/$workspaceId/clusters/'
      path: '/clusters'
      fullPath: '/workspaces/$workspaceId/clusters'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRoute
    }
    '/_authenticated/workspaces/$workspaceId/clusters/$clusterId': {
      id: '/_authenticated/workspaces/$workspaceId/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/workspaces/$workspaceId/clusters/$clusterId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId'
      path: '/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/create': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/create'
      path: '/create'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/create'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/volumes': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/volumes'
      path: '/volumes'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/settings': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/metrics': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/metrics'
      path: '/metrics'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/logs': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/environment': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/environment'
      path: '/environment'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/domains': {
      id: '/_authenticated/workspaces/$workspaceId/projects/_services/$projectId/services/$serviceId/domains'
      path: '/domains'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/domains'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute
    }
  }
}

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesCreateRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdDomainsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdEnvironmentRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdLogsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdMetricsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdSettingsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdVolumesRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesServiceIdRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdServicesRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsServicesProjectIdRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdSettingsRoute:
      AuthenticatedWorkspacesWorkspaceIdSettingsRoute,
    AuthenticatedWorkspacesWorkspaceIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute:
      AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute,
    AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteWithChildren
  AuthenticatedWorkspacesCreateRoute: typeof AuthenticatedWorkspacesCreateRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesWorkspaceIdRoute:
    AuthenticatedWorkspacesWorkspaceIdRouteWithChildren,
  AuthenticatedWorkspacesCreateRoute: AuthenticatedWorkspacesCreateRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
