/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedWorkspacesCreateRouteImport } from './routes/_authenticated/workspaces/create'
import { Route as AuthenticatedWorkspacesWorkspaceIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/settings'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects'
import { Route as AuthenticatedWorkspacesWorkspaceIdClustersRouteImport } from './routes/_authenticated/workspaces/$workspaceId/clusters'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/members/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdClustersIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/clusters/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId'
import { Route as AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/clusters/$clusterId'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
import { Route as AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRouteImport } from './routes/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesCreateRoute =
  AuthenticatedWorkspacesCreateRouteImport.update({
    id: '/workspaces/create',
    path: '/workspaces/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdClustersRoute =
  AuthenticatedWorkspacesWorkspaceIdClustersRouteImport.update({
    id: '/clusters',
    path: '/clusters',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdClustersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdClustersRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdProjectsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute =
  AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRouteImport.update({
    id: '/$clusterId',
    path: '/$clusterId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdClustersRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteImport.update(
    {
      id: '/services',
      path: '/services',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteImport.update(
    {
      id: '/_project_layout',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteImport.update(
    {
      id: '/$serviceId',
      path: '/$serviceId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRouteImport.update(
    {
      id: '/services/',
      path: '/services/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRouteImport.update(
    {
      id: '/volumes',
      path: '/volumes',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRouteImport.update(
    {
      id: '/network',
      path: '/network',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRouteImport.update(
    {
      id: '/metrics',
      path: '/metrics',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRouteImport.update(
    {
      id: '/logs',
      path: '/logs',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRouteImport.update(
    {
      id: '/environment',
      path: '/environment',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/clusters': typeof AuthenticatedWorkspacesWorkspaceIdClustersRouteWithChildren
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/clusters/$clusterId': typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteWithChildren
  '/workspaces/$workspaceId/clusters/': typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
  '/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/clusters/$clusterId': typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  '/workspaces/$workspaceId/clusters': typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
  '/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute
  '/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRouteWithChildren
  '/_authenticated/workspaces/create': typeof AuthenticatedWorkspacesCreateRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceId/clusters': typeof AuthenticatedWorkspacesWorkspaceIdClustersRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects': typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/clusters/$clusterId': typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/clusters/': typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
  '/_authenticated/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute
  '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces'
    | '/workspaces/$workspaceId/clusters'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/clusters/$clusterId'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/clusters/'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects/'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/projects/$projectId/'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/workspaces/create'
    | '/workspaces'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/clusters/$clusterId'
    | '/workspaces/$workspaceId/clusters'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/projects/$projectId/services'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
    | '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/workspaces/create'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceId/clusters'
    | '/_authenticated/workspaces/$workspaceId/projects'
    | '/_authenticated/workspaces/$workspaceId/settings'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/$workspaceId/clusters/$clusterId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId'
    | '/_authenticated/workspaces/$workspaceId/clusters/'
    | '/_authenticated/workspaces/$workspaceId/members/'
    | '/_authenticated/workspaces/$workspaceId/projects/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/'
    | '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/create': {
      id: '/_authenticated/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings': {
      id: '/_authenticated/workspaces/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects': {
      id: '/_authenticated/workspaces/$workspaceId/projects'
      path: '/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/clusters': {
      id: '/_authenticated/workspaces/$workspaceId/clusters'
      path: '/clusters'
      fullPath: '/workspaces/$workspaceId/clusters'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/': {
      id: '/_authenticated/workspaces/$workspaceId/members/'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/clusters/': {
      id: '/_authenticated/workspaces/$workspaceId/clusters/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/clusters/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRoute
    }
    '/_authenticated/workspaces/$workspaceId/clusters/$clusterId': {
      id: '/_authenticated/workspaces/$workspaceId/clusters/$clusterId'
      path: '/$clusterId'
      fullPath: '/workspaces/$workspaceId/clusters/$clusterId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout'
      path: ''
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/_project_layout/services/'
      path: '/services'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
      path: '/volumes'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/volumes'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
      path: '/network'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/network'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
      path: '/metrics'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/metrics'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/logs'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment': {
      id: '/_authenticated/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
      path: '/environment'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/services/$serviceId/environment'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute
    }
  }
}

interface AuthenticatedWorkspacesWorkspaceIdClustersRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute
  AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdClustersRouteChildren: AuthenticatedWorkspacesWorkspaceIdClustersRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute:
      AuthenticatedWorkspacesWorkspaceIdClustersClusterIdRoute,
    AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdClustersIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdClustersRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdClustersRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdClustersRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutSettingsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutServicesIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdEnvironmentRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdLogsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdMetricsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdNetworkRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdSettingsRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdVolumesRoute,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesServiceIdRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdProject_layoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdServicesRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren: AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdProjectsRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdProjectsRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdClustersRoute: typeof AuthenticatedWorkspacesWorkspaceIdClustersRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdProjectsRoute: typeof AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute
}

const AuthenticatedWorkspacesWorkspaceIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdClustersRoute:
      AuthenticatedWorkspacesWorkspaceIdClustersRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdProjectsRoute:
      AuthenticatedWorkspacesWorkspaceIdProjectsRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdSettingsRoute:
      AuthenticatedWorkspacesWorkspaceIdSettingsRoute,
    AuthenticatedWorkspacesWorkspaceIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteWithChildren
  AuthenticatedWorkspacesCreateRoute: typeof AuthenticatedWorkspacesCreateRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesWorkspaceIdRoute:
    AuthenticatedWorkspacesWorkspaceIdRouteWithChildren,
  AuthenticatedWorkspacesCreateRoute: AuthenticatedWorkspacesCreateRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
